const vocabulary = [
  {
    word: "expand",
    translation: "Расширять",
    explanation:
      "to increase in size, number, or importance, or to make something increase in this way.",
    usage: "The air in the balloon expands when heated.",
    module: 1,
  },
  {
    word: "appreciate",
    translation: "Ценить",
    explanation:
      "to recognize how good someone or something is and to value them or it",
    usage:
      "There's no point buying him expensive wines - he doesn't appreciate them.",
    module: 1,
  },
  {
    word: "authentic",
    translation: "Аутентичный",
    explanation:
      "If something is authentic, it is real, true, or what people say it is:",
    usage:
      "He was there and saw what happened, so his is the only authentic account.",
    module: 1,
  },
  {
    word: "authenticity",
    translation: "подлинность",
    explanation: "the quality of being real or true",
    usage: "Many people now question the authenticity of his claims.'.",
    module: "Module 1",
  },
  {
    word: "be used to doing",
    translation: "привыкнуть (к выполнению чего-либо)",
    explanation:
      "This phrase is used to express being accustomed to a specific action or situation. It consists of the verb 'be' in the correct tense, followed by 'used to' and a verb in the '-ing' form. For example: 'I am used to waking up early.'",
    usage: "I am used to working long hours, so it doesn't bother me anymore.",
    module: "Module 1",
  },
  {
    word: "burst out",
    translation: "вырвалось на ружу",
    explanation: "to suddenly say something loudly.",
    usage: "Don't go! he burst out'.",
    module: "Module 1",
  },
  {
    word: "ceremony",
    translation: "церемония",
    explanation:
      "formal acts, often fixed and traditional, performed on important social or religious occasions:.",
    usage: "The Olympics climaxed in a spectacular closing ceremony.'.",
    module: "Module 1",
  },
  {
    word: "checklist",
    translation: "контрольный список",
    explanation:
      "a list of things that you must think about, or that you must remember to do:.",
    usage: "I have a checklist of things that I must do today.'.",
    module: "Module 1",
  },
  {
    word: "coach",
    translation: "тренер",
    explanation:
      "someone whose job is to teach people to improve at a sport, skill, or school subject:.",
    usage:
      "Our football coach has worked hard to inculcate a team spirit into the players.'.",
    module: "Module 1",
  },
  {
    word: "custom",
    translation: "обычай",
    explanation:
      "a way of behaving or a belief that has been established for a long time:",
    usage: "'She covered her head out of deference to Muslim custom..",
    module: "Module 1",
  },
  {
    word: "define",
    translation: "определить",
    explanation: "to say what the meaning of something, especially a word, is.",
    usage:
      "Before I answer your question, could you define your terms a little more.",
    module: "Module 1",
  },
  {
    word: "deliberately",
    translation: "умышленно",
    explanation: "intentionally.",
    usage: "He did it deliberately to annoy me.'.",
    module: "Module 1",
  },
  {
    word: "district",
    translation: "район, округ",
    explanation:
      "an area of a country or town that has fixed borders that are used for official purposes, or that has a particular feature that makes it different from surrounding areas:",
    usage:
      "Vandals smashed windows and overturned cars in the downtown shopping district..",
    module: "Module 1",
  },
  {
    word: "dormitory",
    translation: "общежитие",
    explanation:
      "a large building at a college or university where students live",
    usage: "I dream of getting into our college dormitory'.",
    module: "Module 1",
  },
  {
    word: "editor",
    translation: "редактор",
    explanation:
      "a person who corrects or changes pieces of text or films before they are printed or shown, or a person who is in charge of a newspaper or magazine:",
    usage:
      "She's a senior editor in the reference department of a publishing company..",
    module: "Module 1",
  },
  {
    word: "elderly",
    translation: "пожилые люди",
    explanation: "polite word for old",
    usage: "William is nearly 50, and his parents are elderly.",
    module: "Module 1",
  },
  {
    word: "elsewhere",
    translation: "в другом месте",
    explanation:
      "at, in, from, or to another place or other places; anywhere or somewhere else.",
    usage: "The report looks at economic growth in Europe and elsewhere..",
    module: "Module 1",
  },
  {
    word: "emphasise",
    translation: "подчёркивать",
    explanation:
      "to show that something is very important or worth giving attention to:",
    usage:
      "I'd just like to emphasize how important it is for people to learn foreign languages.",
    module: "Module 1",
  },
  {
    word: "encounter(n).",
    translation: "подчёркивать",
    explanation:
      "to show that something is very important or worth giving attention to:",
    usage:
      "I'd just like to emphasize how important it is for people to learn foreign languages.",
    module: "Module 1",
  },
  {
    word: "entertain",
    translation: "развлекать",
    explanation: "to keep a group of people interested or enjoying themselves.",
    usage:
      "Most children's television programmes aim to educate and entertain at the same time'.",
    module: "Module 1",
  },
  {
    word: "Immerse",
    translation: "погружаться",
    explanation:
      "to put something or someone completely under the surface of a liquid",
    usage: "The shells should be immersed in boiling water for two minutes.",
    module: "Module 1",
  },
  {
    word: "insight",
    translation: "понимание",
    explanation:
      " a clear, deep, and sometimes sudden understanding of a complicated problem or situation:.",
    usage:
      "The documentary offers an insight into the everyday lives of millions of ordinary Russian citizens..",
    module: "Module 1",
  },
  {
    word: "kimono",
    translation: "кимано",
    explanation:
      "a long, loose piece of outer clothing with very wide sleeves, traditionally worn by the Japanese.",
    usage: "this is beautiful kimono.",
    module: "Module 1",
  },
  {
    word: "lagoon",
    translation: "лагуна",
    explanation:
      "an area of sea water separated from the sea by a reef (= a line of rocks and sand):.",
    usage:
      "The incubation bottles were then removed, and the samples rinsed several times with washes of ' cold ' lagoon water..",
    module: "Module 1",
  },
  {
    word: "lively",
    translation: "живой",
    explanation: "full of energy and enthusiasm; interesting and exciting :.",
    usage: "There was some lively discussion at the meeting.",
    module: "Module 1",
  },
  {
    word: "meaningful",
    translation: "значимый",
    explanation: "intended to show meaning, often secretly",
    usage: "He raised one eyebrow in a meaningful way.",
    module: "Module 1",
  },
  {
    word: "natural",
    translation: "естественный",
    explanation:
      "as found in nature and not involving anything made or done by people",
    usage:
      "'.People say that breast-feeding is better than bottle-feeding because it's more natural.",
    module: "Module 1",
  },
  {
    word: "leave a lot to be desired",
    translation: "оставляет желать лучшего",
    explanation: "to be much worse than you would like",
    usage: "Apparently, Meg's cooking leaves a lot to be desired.",
    module: "Module 1",
  },
  {
    word: "sweep",
    translation: "мести-подметать",
    explanation:
      "to clean something, especially a floor by using a brush to collect the dirt into one place from which it can be removed.",
    usage: "American minesweepers are sweeping the Arabian Sea..",
    module: "Module 1",
  },
  {
    word: "turquoise",
    translation: "бирюзовый",
    explanation:
      "a bluish-green semi-precious stone that is often used in jewellery",
    usage: "the clear turquoise water of the bay.",
    module: "Module 1",
  },
  {
    word: "aisle",
    translation: "ряд",
    explanation:
      "a long, narrow space between rows of seats in an aircraft, cinema, or church.",
    usage:
      "You'll find the shampoo and the soap in the fourth aisle from the entrance..",
    module: "Module 1",
  },
  {
    word: "ambition",
    translation: "амбиции",
    explanation: "a strong wish to achieve something.",
    usage:
      "He has already achieved his main ambition in life - to become wealthy.'.",
    module: "Module 1",
  },
  {
    word: "ambllous",
    translation: "амблюзивный",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'ambllous'.",
    module: "Module 1",
  },
  {
    word: "appeal",
    translation: "обращаться",
    explanation: "a request to the public for money, information, or help.",
    usage:
      "The police have issued an appeal to the public to stay away from the area over the weekend..",
    module: "Module 1",
  },
  {
    word: "appealing",
    translation: "привлекательный",
    explanation: "attractive or interesting.",
    usage: "He had a nice smile and an appealing personality..",
    module: "Module 1",
  },
  {
    word: "bride",
    translation: "невеста",
    explanation: "a woman who is about to get married or has just got married",
    usage: "He returned from New York with his lovely new bride..",
    module: "Module 1",
  },
  {
    word: "considerable",
    translation: "значительный",
    explanation: "large or of noticeable importance.",
    usage: "The fire caused considerable damage to the church..",
    module: "Module 1",
  },
  {
    word: "decisive",
    translation: "решительный",
    explanation:
      "able to make decisions quickly and confidently, or showing this quality.",
    usage:
      "These results could prove decisive in establishing the criminal's identity.",
    module: "Module 1",
  },
  {
    word: "differ",
    translation: "отличаться-различаться",
    explanation:
      "to be not like something or someone else, either physically or in another way.",
    usage:
      "Eye-witness accounts of the fighting differ markedly from police reports of what happened..",
    module: "Module 1",
  },
  {
    word: "distinguish",
    translation: "различать",
    explanation:
      "to notice or understand the difference between two things, or to make one person or thing seem different from another.",
    usage: "It's important to distinguish between business and pleasure.'.",
    module: "Module 1",
  },
  {
    word: "distinguished",
    translation: "выдающийся",
    explanation:
      "used to describe a respected and admired person, or their work.",
    usage: "a distinguished career.",
    module: "Module 1",
  },
  {
    word: "effect",
    translation: "эффект",
    explanation: "the result of a particular influence.",
    usage:
      "I tried taking tablets for the headache but they didn't have any effect.'.",
    module: "Module 1",
  },
  {
    word: "effective",
    translation: "эфективный",
    explanation: "successful or achieving the results that you want.",
    usage:
      "The lighting for the production made a very effective use of shadow.",
    module: "Module 1",
  },
  {
    word: "envious",
    translation: "завистливый",
    explanation: "wishing you had what another person has",
    usage: "envious of I'm very envious of your new coat - it's beautiful",
    module: "Module 1",
  },
  {
    word: "envy",
    translation: "завидовать",
    explanation: "to wish that you had something that another person has.",
    usage: "I envy her ability to talk to people she's never met before.",
    module: "Module 1",
  },
  {
    word: "Imaginary",
    translation: "воображаемый",
    explanation:
      "Something that is imaginary is created by and exists only in the mind.",
    usage: "As a child I had an imaginary friend.",
    module: "Module 1",
  },
  {
    word: "immigrant",
    translation: "иммигрант",
    explanation:
      "a person who has come to a different country in order to live there permanently",
    usage:
      "immigrant population The surrounding area has a large immigrant population.",
    module: "Module 1",
  },
  {
    word: "informative",
    translation: "информативный",
    explanation: "providing a lot of useful information",
    usage: "This is an interesting and highly informative book.",
    module: "Module 1",
  },
  {
    word: "initial",
    translation: "исходный",
    explanation: "of or at the beginning.",
    usage:
      "Initial reports say that seven people have died, though this has not yet been confirmed.",
    module: "Module 1",
  },
  {
    word: "memorable",
    translation: "памятный",
    explanation: "likely to be remembered or worth remembering.",
    usage:
      "T haven't seen them since that memorable evening when the boat capsized..",
    module: "Module 1",
  },
  {
    word: "observant",
    translation: "наблюдательный",
    explanation: "good or quick at noticing things",
    usage: "That's a new dress, isn't it? Yes, you are observant!.",
    module: "Module 1",
  },
  {
    word: "observe",
    translation: "наблюдать",
    explanation:
      "to watch carefully the way something happens or the way someone does something, especially in order to learn more about it:.",
    usage:
      "The role of scientists is to observe and describe the world, not to try to control it.",
    module: "Module 1",
  },
  {
    word: "overwhelm",
    translation: "подавлять",
    explanation: "to defeat someone or something by using a lot of force.",
    usage:
      "Government troops have overwhelmed the rebels and seized control of the capital.",
    module: "Module 1",
  },
  {
    word: "overwhelmed",
    translation: "перегруженный",
    explanation: "to be too much to deal with.",
    usage:
      "The number of refugees overwhelmed the relief agencies in the area.",
    module: "Module 1",
  },
  {
    word: "pricey",
    translation: "дорогой",
    explanation: "expensive.",
    usage: "'It's a bit pricey but the food is wonderful.",
    module: "Module 1",
  },
  {
    word: "primary",
    translation: "начальный",
    explanation: "more important than anything else; main",
    usage:
      "The Red Cross's primary concern is to preserve and protect human life.",
    module: "Module 1",
  },
  {
    word: "sensible",
    translation: "разумный",
    explanation:
      "based on or acting on good judgment and practical ideas or understanding",
    usage: "I think the sensible thing to do is call and ask for directions",
    module: "Module 1",
  },
  {
    word: "stressed out",
    translation: "стресс",
    explanation: "worried and nervous.",
    usage:
      "The kids are sick, I just lost my baby-sitter, and our toilet doesn’t work  no wonder I feel stressed-out!.",
    module: "Module 1",
  },
  {
    word: "strict",
    translation: "строгий",
    explanation:
      "strongly limiting someone's freedom to behave as they wish, or likely to severely punish someone if they do not obey.",
    usage: "My parents were very strict with me when I was young.",
    module: "Module 1",
  },
  {
    word: "thoughtful",
    translation: "вдумчивый-задумчивый",
    explanation: "quiet because you are thinking about something",
    usage: "You look thoughtful'.",
    module: "Module 1",
  },
  {
    word: "trend",
    translation: "тренд",
    explanation:
      "a general development or change in a situation or in the way that people are behaving:.",
    usage:
      "Surveys show a trend away from home-ownership and toward rented accommodation.s is an example sentence using the word 'trend'.",
    module: "Module 1",
  },
  {
    word: "a keen eye",
    translation: "острый глаз",
    explanation:
      "This phrase refers to the ability to notice or perceive small details or subtle differences, often used to describe someone who is observant or detail-oriented. For example: 'She has a keen eye for fashion trends.'",
    usage: "He has a keen eye for spotting errors in documents.",
    module: "Module 1",
  },
  {
    word: "alike",
    translation: "одинаково",
    explanation: "similar to each other",
    usage: "look alike The children all look very alike.",
    module: "Module 1",
  },
  {
    word: "amphitheatre",
    translation: "амфитеатр",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'amphitheatre'.",
    module: "Module 1",
  },
  {
    word: "atfirst glance",
    translation: "на первый взгляд",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'atfirst glance'.",
    module: "Module 1",
  },
  {
    word: "be present",
    translation: "присутствовать",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'be present'.",
    module: "Module 1",
  },
  {
    word: "bravery",
    translation: "храбрость",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'bravery'.",
    module: "Module 1",
  },
  {
    word: "cloth",
    translation: "ткань",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'cloth'.",
    module: "Module 1",
  },
  {
    word: "dot",
    translation: "точка",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'dot'.",
    module: "Module 1",
  },
  {
    word: "emblem",
    translation: "эмблема",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'emblem'.",
    module: "Module 1",
  },
  {
    word: "equal",
    translation: "равный",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'freedom'.",
    module: "Module 1",
  },
  {
    word: "fabric",
    translation: "ткань",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'horlzontal'.",
    module: "Module 1",
  },
  {
    word: "feature",
    translation: "особенность",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'Identical'.",
    module: "Module 1",
  },
  {
    word: "independence",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'independence'.",
    module: "Module 1",
  },
  {
    word: "Jnfluence",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'Jnfluence'.",
    module: "Module 1",
  },
  {
    word: "Innocence",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'Innocence'.",
    module: "Module 1",
  },
  {
    word: "Inspire",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'Inspire'.",
    module: "Module 1",
  },
  {
    word: "justice",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'justice'.",
    module: "Module 1",
  },
  {
    word: "material",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'material'.",
    module: "Module 1",
  },
  {
    word: "rational anthem",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'rational anthem'.",
    module: "Module 1",
  },
  {
    word: "popularity",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'popularity'.",
    module: "Module 1",
  },
  {
    word: "pride",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'pride'.",
    module: "Module 1",
  },
  {
    word: "rectangle",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'rectangle'.",
    module: "Module 1",
  },
  {
    word: "represent",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'represent'.",
    module: "Module 1",
  },
  {
    word: "representation",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'representation'.",
    module: "Module 1",
  },
  {
    word: "semicircle",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'semicircle'.",
    module: "Module 1",
  },
  {
    word: "shade",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'shade'.",
    module: "Module 1",
  },
  {
    word: "source",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'source'.",
    module: "Module 1",
  },
  {
    word: "stripe",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'stripe'.",
    module: "Module 1",
  },
  {
    word: "sword",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'sword'.",
    module: "Module 1",
  },
  {
    word: "symbol",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'symbol'.",
    module: "Module 1",
  },
  {
    word: "symbolise",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'symbolise'.",
    module: "Module 1",
  },
  {
    word: "tell apart",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'tell apart'.",
    module: "Module 1",
  },
  {
    word: "triangle",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'triangle'.",
    module: "Module 1",
  },
  {
    word: "typical",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'typical'.",
    module: "Module 1",
  },
  {
    word: "vary",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'vary'.",
    module: "Module 1",
  },
  {
    word: "vertical",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'vertical'.",
    module: "Module 1",
  },
  {
    word: "awareness",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'awareness'.",
    module: "Module 1",
  },
  {
    word: "awkward",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'awkward'.",
    module: "Module 1",
  },
  {
    word: "be of no value",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'be of no value'.",
    module: "Module 1",
  },
  {
    word: "beliet",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'beliet'.",
    module: "Module 1",
  },
  {
    word: "cheek",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'cheek'.",
    module: "Module 1",
  },
  {
    word: "credible",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'credible'.",
    module: "Module 1",
  },
  {
    word: "current affairs",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'current affairs'.",
    module: "Module 1",
  },
  {
    word: "fragile",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'fragile'.",
    module: "Module 1",
  },
  {
    word: "heritage",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'heritage'.",
    module: "Module 1",
  },
  {
    word: "historian",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'historian'.",
    module: "Module 1",
  },
  {
    word: "misunderstand",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'misunderstand'.",
    module: "Module 1",
  },
  {
    word: "native speaker",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'native speaker'.",
    module: "Module 1",
  },
  {
    word: "origin",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'origin'.",
    module: "Module 1",
  },
  {
    word: "overhear",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'overhear'.",
    module: "Module 1",
  },
  {
    word: "Practical joke",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'Practical joke'.",
    module: "Module 1",
  },
  {
    word: "reserve",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'reserve'.",
    module: "Module 1",
  },
  {
    word: "values",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'values'.",
    module: "Module 1",
  },
  {
    word: "Phrases",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'Phrases'.",
    module: "Module 1",
  },
  {
    word: "auction",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'auction'.",
    module: "Module 1",
  },
  {
    word: "background",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'background'.",
    module: "Module 1",
  },
  {
    word: "drop sb aline",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'drop sb aline'.",
    module: "Module 1",
  },
  {
    word: "for one's liking",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'for one's liking'.",
    module: "Module 1",
  },
  {
    word: "hesitate",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'hesitate'.",
    module: "Module 1",
  },
  {
    word: "importance",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'importance'.",
    module: "Module 1",
  },
  {
    word: "foads of",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'foads of'.",
    module: "Module 1",
  },
  {
    word: "mingle",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'mingle'.",
    module: "Module 1",
  },
  {
    word: "multicultural",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'multicultural'.",
    module: "Module 1",
  },
  {
    word: "national holiday",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'national holiday'.",
    module: "Module 1",
  },
  {
    word: "regards",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'regards'.",
    module: "Module 1",
  },
  {
    word: "session",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'session'.",
    module: "Module 1",
  },
  {
    word: "tea set",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'tea set'.",
    module: "Module 1",
  },
  {
    word: "variety",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'variety'.",
    module: "Module 1",
  },
  {
    word: "Phrases",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'Phrases'.",
    module: "Module 1",
  },
  {
    word: "See for yourself",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'See for yourself'.",
    module: "Module 1",
  },
  {
    word: "a thirst for knowledae",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage:
      "This is an example sentence using the word 'a thirst for knowledae'.",
    module: "Module 1",
  },
  {
    word: "vanish",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'vanish'.",
    module: "Module 1",
  },
  {
    word: "ahead",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'ahead'.",
    module: "Module 1",
  },
  {
    word: "aircraft",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'aircraft'.",
    module: "Module 1",
  },
  {
    word: "aspect",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'aspect'.",
    module: "Module 1",
  },
  {
    word: "be bound to",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'be bound to'.",
    module: "Module 1",
  },
  {
    word: "bright",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'bright'.",
    module: "Module 1",
  },
  {
    word: "challenging",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'challenging'.",
    module: "Module 1",
  },
  {
    word: "concerning",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'concerning'.",
    module: "Module 1",
  },
  {
    word: "conventional",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'conventional'.",
    module: "Module 1",
  },
  {
    word: "crucial",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'crucial'.",
    module: "Module 1",
  },
  {
    word: "curriculum",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'curriculum'.",
    module: "Module 1",
  },
  {
    word: "demanding",
    translation: "Placeholder translation",
    explanation: "Placeholder explanation for the word.",
    usage: "This is an example sentence using the word 'rastically'.",
    module: "Module 1",
  },

  {
    word: "determine",
    translation: "определять",
    explanation:
      "to discover the facts about something; to calculate something exactly",
    usage: "The scientists are working to determine the cause of the disease.",
    module: "Module 1",
  },
  {
    word: "drastically",
    translation: "радикально",
    explanation: "in an extreme or sudden way",
    usage: "The company drastically reduced its workforce to cut costs.",
    module: "Module 1",
  },
  {
    word: "edible",
    translation: "съедобный",
    explanation: "safe or suitable to be eaten",
    usage: "These berries are not edible and can make you sick.",
    module: "Module 1",
  },
  {
    word: "enrol",
    translation: "записываться",
    explanation: "to officially join a course, school, or group",
    usage: "She decided to enrol in a cooking class.",
    module: "Module 1",
  },
  {
    word: "excel",
    translation: "преуспевать",
    explanation: "to be very good at doing something",
    usage: "He excels in mathematics and science.",
    module: "Module 1",
  },
  {
    word: "fall behind",
    translation: "отставать",
    explanation: "to not make as much progress as others",
    usage: "She started to fall behind in her studies.",
    module: "Module 1",
  },
  {
    word: "field trip",
    translation: "экскурсия",
    explanation:
      "a trip made by students to study something in its natural environment",
    usage: "The class went on a field trip to the museum.",
    module: "Module 1",
  },
  {
    word: "focused",
    translation: "сосредоточенный",
    explanation: "giving all your attention to something",
    usage: "She remained focused throughout the competition.",
    module: "Module 1",
  },
  {
    word: "gifted",
    translation: "одарённый",
    explanation: "having a natural ability to do something very well",
    usage: "He is a gifted musician.",
    module: "Module 1",
  },
  {
    word: "identify",
    translation: "определять",
    explanation: "to recognize and name someone or something",
    usage: "We need to identify the problem before fixing it.",
    module: "Module 1",
  },
  {
    word: "intimidated",
    translation: "запуганный",
    explanation: "feeling frightened or nervous due to someone or something",
    usage: "She felt intimidated by the large audience.",
    module: "Module 1",
  },
  {
    word: "intriguing",
    translation: "увлекательный",
    explanation: "very interesting because it is unusual or mysterious",
    usage: "The book offers an intriguing mystery.",
    module: "Module 1",
  },
  {
    word: "lack",
    translation: "недоставать",
    explanation: "to not have something or enough of something",
    usage: "They lack the resources needed for the project.",
    module: "Module 1",
  },
  {
    word: "maintain",
    translation: "поддерживать",
    explanation: "to keep something in good condition",
    usage: "It’s important to maintain a healthy diet.",
    module: "Module 1",
  },
  {
    word: "patient",
    translation: "терпеливый",
    explanation: "able to accept delays or problems without becoming annoyed",
    usage: "You need to be patient when working with children.",
    module: "Module 1",
  },
  {
    word: "pick up",
    translation: "научиться",
    explanation: "to learn something informally",
    usage: "He picked up French while living in Paris.",
    module: "Module 1",
  },
  {
    word: "poisonous",
    translation: "ядовитый",
    explanation: "containing poison that is harmful or deadly",
    usage: "Be careful; some mushrooms are poisonous.",
    module: "Module 1",
  },
  {
    word: "remarkably",
    translation: "удивительно",
    explanation: "in an unusual or surprising way",
    usage: "The baby is remarkably calm.",
    module: "Module 1",
  },
  {
    word: "remind",
    translation: "напоминать",
    explanation: "to make someone remember something",
    usage: "Can you remind me to call my mom?",
    module: "Module 1",
  },
  {
    word: "shelter",
    translation: "укрытие",
    explanation: "a place giving protection from bad weather or danger",
    usage: "We took shelter under a tree during the rain.",
    module: "Module 1",
  },
  {
    word: "struggle",
    translation: "бороться",
    explanation: "to try very hard to do something difficult",
    usage: "She struggled to finish her homework on time.",
    module: "Module 1",
  },
  {
    word: "survival",
    translation: "выживание",
    explanation: "the state of continuing to live or exist",
    usage: "Food and water are essential for survival.",
    module: "Module 1",
  },
  {
    word: "the great outdoors",
    translation: "великолепная природа",
    explanation: "the open countryside, especially for activities like camping",
    usage: "He loves spending time in the great outdoors.",
    module: "Module 1",
  },
  {
    word: "tracks",
    translation: "следы",
    explanation: "marks left by a person, animal, or vehicle",
    usage: "We followed the tracks in the snow.",
    module: "Module 1",
  },
  {
    word: "wilderness",
    translation: "дикая местность",
    explanation: "a natural area of land not used by humans",
    usage: "They went camping in the wilderness.",
    module: "Module 1",
  },
  {
    word: "woods",
    translation: "лес",
    explanation: "an area of land covered with trees",
    usage: "They went for a walk in the woods.",
    module: "Module 1",
  },
];

export default vocabulary;
